### ISSUE TITLE
GUI?

### ISSUE THREAD

**Issue by PySimpleGUI** [aaronpenne/generative_art#3]
I've not played with your stuff much yet, so maybe this is all already answered.

Do you have a GUI version of your program?  I see instructions for launching from the command line and outputting to a file.  I was wondering if you've considered adding a GUI.  

I would be interested in adding something onto what you've got.  It would likely be quite easy to do.  I'm not sure exactly what to include however.  Such as, how would you like to see selection of creating a particular piece / type of art?  Would it be a scan of the available .py files in the folders?  I'm guessing as I play with what you've got that will answer itself.

If you're interested in adding a GUI, let me know and I'll look into what it'll take to drop a PySimpleGUI GUI onto what you've got.  If you have a sketch for what you think a GUI would look like, that would be awesome to see too.

**Comment by aaronpenne** [comment]
Hello, love the idea, but most of the .py code here is actually .pyde and used in the Processing framework's Python mode. py.processing.org

There are possibilities for GUI on a sketch by sketch basis using [controlP5](https://github.com/sojamo/controlp5/) or similar.

Thanks for your interest, closing the issue.
