### ISSUE TITLE
reimplemented butterfly using C# and SkiaSharp

### ISSUE THREAD

**Issue by taurenshaman** [aaronpenne/generative_art#4]
The code: [AaronPenneButterfly](https://github.com/taurenshaman/veins.skiasharp/blob/master/Veins.SkiaSharp/Veins.Art/Livings/AaronPenneButterfly.cs)

Also I found a little small "bug", Maybe it's because of the implementation difference between SkiaSharp and Processing:  
![butterfly-error-1](https://user-images.githubusercontent.com/1308706/100694797-bbacb380-33ca-11eb-9f4c-dbbd3ad8afa5.png)
![butterfly-error-2](https://user-images.githubusercontent.com/1308706/100694800-bd767700-33ca-11eb-98da-d9224084b20a.png)
![butterfly-error-3](https://user-images.githubusercontent.com/1308706/100694801-be0f0d80-33ca-11eb-83ed-87f265af7bcb.png)

My solution:  append the actual start point to the `16_points` list:
```
List<SKPoint> get_16_points(float x, float y, float w, float h) {
      float squeeze = RandomUtility.CreateRandom( -w * 0.2f, w * 0.2f );
      List<SKPoint> points = new List<SKPoint>();
      points.Add( new SKPoint( x, y ) );
      points.Add( new SKPoint( x + w * 0.25f, y ) );
      points.Add( new SKPoint( x + w * 0.5f, y - h * 0.05f ) );
      points.Add( new SKPoint( x + w * 0.75f, y ) );

      points.Add( new SKPoint( x + w, y ) );
      points.Add( new SKPoint( x + w, y + h * 0.25f ) );
      points.Add( new SKPoint( x + w + squeeze, y + h * 0.5f ) );
      points.Add( new SKPoint( x + w, y + h * 0.75f ) );

      points.Add( new SKPoint( x + w, y + h ) );
      points.Add( new SKPoint( x + w * 0.75f, y + h ) );
      points.Add( new SKPoint( x + w * 0.5f, y + h ) );
      points.Add( new SKPoint( x + w * 0.25f, y + h ) );

      points.Add( new SKPoint( x, y + h ) );
      points.Add( new SKPoint( x, y + h * 0.75f ) );
      points.Add( new SKPoint( x - squeeze, y + h * 0.5f ) );
      points.Add( new SKPoint( x, y + h * 0.25f ) );

      points.RemoveAt( 12 );
      points.RemoveAt( 8 );
      points.RemoveAt( 4 );
      points.RemoveAt( 0 );

      points.Add( new SKPoint( x + w * 0.25f, y ) ); // Hack Code

      return points;
}
```
Thanks for your time and work!
❤❤❤❤❤❤❤

**Comment by aaronpenne** [comment]
Glad you dug into this butterfly code! Interesting to see SkiaSharp, I had not heard of it. Best of luck on your generative artwork explorations!

Closing as there is no issue with original code, only on porting to SkiaSharp.
