### ISSUE TITLE
offset_blob in the geode.pyde

### ISSUE THREAD

**Issue by soilstack** [aaronpenne/generative_art#5]
There is a variable `offset_blob`.    It's initialized to zero,  set to a global, and incremented during the drawing loop, but I don't ever see it used in any calculation or referenced in any other way in the script.   

Wondered if this is extraneous code that should have been deleted, or if I'm misunderstanding something. Was just reading through the code to get an idea of 'idiomatic' python-processing code.

**Comment by aaronpenne** [comment]
In the old days I copy/pasted code regularly from one project to the next. The focus was on quick iteration in order to express an idea and create artwork. There are likely several vestigial artifacts. Well done stepping through the code. Go ahead and ignore it.
