### ISSUE TITLE
Nonfree license

### ISSUE THREAD

**Issue by TechnologyClassroom** [aaronpenne/generative_art#6]
I noticed your license (CC-BY-NC-4.0) uses NC which is a nonfree license. I would recommend using CC-BY-SA-4.0 instead.

**Comment by aaronpenne** [comment]
I am using a non-commercial license because I do not want people to use this code for commercial purposes. Thank you for the recommendation, but I'm happy with the current license.

**Comment by TechnologyClassroom** [comment]
I get that.  Selling others work with CC-BY-SA is awkward and rarely happens because the seller would have to give proper attribution and share changes or be in violation of the license.

With the current license, a long term community surrounding these projects is impractical.  When the amount of contributors grows, the difficulty of getting everyone to agree to a license change becomes difficult or impossible.  CC NC is a look-at-what-i-did-but-do-not-touch license.

**Comment by aaronpenne** [comment]
I share this artwork code in an effort to let people interested in generative artwork have some references and end-to-end examples by way of seeing the internals of my work. "Look but don't touch" is exactly how I want it used. This is not a framework or a tool to build off of, it is simply an artist sharing their methods.

My artwork code from this repo was used in a widespread NFT scam, so I have to be more strict about licensing, unfortunately. My gut reaction after that scam was to take all of this code down, but felt that would do more harm than good, as I truly care about the community and want to give new artists an opportunity to see one way of doing things.
